[package]
name = "c_fuzzing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo-fuzz = "0.11.2"
serde_json = "1.0.103"

[build-dependencies]
bindgen = "0.65.1"
