name: "Fuzzer Workflow"
on: workflow_dispatch
jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}

    - name: Cache Inputs
      id: cache-inputs
      uses: actions/cache@v3
      with:
        path: test_fuzzer/hfuzz_workspace/input
        key: ${{ runner.os }}-inputs

    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
        sudo apt-get install binutils-dev
        sudo apt-get install libunwind-dev
        sudo curl https://sh.rustup.rs -sSf | bash -s -- -y --default-toolchain nightly

    - name: Set Environment Variable
      run: echo "PATH="/root/.cargo/bin:${PATH}"" >> $GITHUB_ENV

    - name: Install Honggfuzz
      run: cargo install honggfuzz
      
    - name: Initializing fuzzer with previous inputs 
      run: |
        cd test_fuzzer
        HFUZZ_RUN_ARGS="--run_time 5" cargo hfuzz run test_fuzzer
        HFUZZ_RUN_ARGS="--minimize" cargo hfuzz run test_fuzzer

    # - uses: stefanzweifel/git-auto-commit-action@v4
    #   with:
    #     commit_message: changing report
    #     file_pattern: '*/hfuzz_workspace/test_fuzzer/HONGGFUZZ*  */hfuzz_workspace/test_fuzzer/SIG*'

    - name: Checkout commits  
      uses: actions/checkout@v2
      with:
        # Checkout as many commits as needed for the diff
        fetch-depth: 2
    - name: Check diff
      shell: pwsh
      # Give an id to the step, so we can reference it later
      id: check_file_changed
      run: |
        # Diff HEAD with the previous commit
        $diff = git diff --name-only HEAD^ HEAD

        # Check if honggfuzz report has changed and new crash dump was added.
        $SourceDiff = $diff | Where-Object { $_ -match '*/hfuzz_workspace/test_fuzzer/HONGGFUZZ*' -or $_ -match '*/hfuzz_workspace/test_fuzzer/SIG*' }
        $HasDiff = $SourceDiff.Length -gt 0

        # Set the output named "docs_changed"
        Write-Host "::set-output name=docs_changed::$HasDiff"

    - name: Create issue 
      shell: pwsh
      # steps.<step_id>.outputs.<output name>
      if: steps.check_file_changed.outputs.docs_changed == 'True'
      uses: JasonEtco/create-an-issue@v2
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
