name: "Fuzzer Workflow"
on: workflow_dispatch
jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Cache Inputs
      id: cache-inputs
      uses: actions/cache@v3
      with:
        path: test_fuzzer/hfuzz_workspace/input
        key: ${{ runner.os }}-inputs

    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
        sudo apt-get install binutils-dev
        sudo apt-get install libunwind-dev
        sudo curl https://sh.rustup.rs -sSf | bash -s -- -y --default-toolchain nightly

    - name: Set Environment Variable
      run: echo "PATH="/root/.cargo/bin:${PATH}"" >> $GITHUB_ENV

    - name: Install Honggfuzz
      run: cargo install honggfuzz
      
    - name: Initializing fuzzer with previous inputs 
      run: |
        cd test_fuzzer
        HFUZZ_RUN_ARGS="--run_time 5" cargo hfuzz run test_fuzzer
        HFUZZ_RUN_ARGS="--minimize" cargo hfuzz run test_fuzzer

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: changing report
        file_pattern: '*/hfuzz_workspace/test_fuzzer/HONGGFUZZ*  */hfuzz_workspace/test_fuzzer/SIG*'

    - name: Checkout commits  
      uses: actions/checkout@v2
      with:
        # Checkout as many commits as needed for the diff
        fetch-depth: 2
    - name: Check diff
      uses: tj-actions/verify-changed-files@v16
      id: check_file_changed
      with:
        files: |
          */hfuzz_workspace/test_fuzzer/HONGGFUZZ*
          */hfuzz_workspace/test_fuzzer/SIG*

    - name: Create issue 
      uses: JasonEtco/create-an-issue@v2
      # steps.<step_id>.outputs.<output name>
      if: steps.check_file_changed.outputs.files_changed == 'true'
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
